"""Generate the transport-only TypeScript contract from Pydantic, without an API call.

Run from backend: python scripts/export_ai_types.py [--check]
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from app.ai.contracts import InvestigationResult, InvestigationTrigger


def ts(schema: dict, *, response: bool = True) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(ts(item, response=response) for item in schema["anyOf"])
    kind = schema.get("type")
    if kind == "array":
        return f"Array<{ts(schema['items'], response=response)}>"
    if kind == "object":
        if "properties" not in schema:
            return f"Record<string, {ts(schema.get('additionalProperties', {}))}>"
        required = set(schema.get("required", []))
        fields = [
            f"  {key}{'' if response or key in required else '?'}: {ts(value, response=response)}"
            for key, value in schema["properties"].items()
        ]
        return "{\n" + "\n".join(fields) + "\n}"
    return {"string": "string", "integer": "number", "number": "number", "boolean": "boolean", "null": "null"}.get(kind, "unknown")


def generate() -> str:
    result = InvestigationResult.model_json_schema(mode="serialization")
    trigger = InvestigationTrigger.model_json_schema(mode="validation")
    definitions = dict(sorted(result.get("$defs", {}).items()))
    lines = ["// Generated by backend/scripts/export_ai_types.py. Do not edit by hand."]
    lines += [f"export type {key} = " + (
        "string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue }"
        if key == "JsonValue" else ts(value)
    ) for key, value in definitions.items()]
    lines += [f"export type InvestigationResult = {ts(result)}"]
    lines += [f"export type InvestigationTriggerInput = {ts(trigger, response=False)}"]
    return "\n\n".join(lines) + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = Path(__file__).resolve().parents[2] / "src/lib/api/types/ai.ts"
    content = generate()
    if args.check:
        if not target.exists() or target.read_text(encoding="utf-8") != content:
            raise SystemExit("AI transport types differ from the backend contracts; regenerate them.")
    else:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8", newline="\n")
