// Generated by backend/scripts/export_ai_types.py. Do not edit by hand.

export type ConfidenceLevel = "LOW" | "MEDIUM" | "HIGH"

export type Contradiction = {
  description: string
  evidence_ids: Array<string>
}

export type ContributingFactor = {
  statement: string
  evidence_ids: Array<string>
}

export type DiagnosisStatus = "CONFIRMED" | "PROBABLE" | "INCONCLUSIVE"

export type EvidenceItem = {
  evidence_id: string
  kind: EvidenceKind
  source_tool: string
  source_service: string
  metric: string
  value: JsonValue
  available: boolean
  status: EvidenceStatus | null
  unit: string | null
  site_id: number | null
  shift_id: number | null
  equipment_id: number | null
  zone_id: number | null
  observed_at: string | null
  source_record_ids: Array<string>
  metadata: Record<string, JsonValue>
  notes: string | null
}

export type EvidenceKind = "FACT" | "DERIVED_METRIC" | "MODEL_PREDICTION" | "OPERATOR_FEEDBACK"

export type EvidenceRequest = {
  request_id: string
  request_type: EvidenceRequestType
  equipment_id: number | null
  zone_id: number | null
  start_time: string | null
  end_time: string | null
  parameters: Array<string>
  reason: string
}

export type EvidenceRequestAttempt = {
  signature: string
  request: EvidenceRequest
  outcome: EvidenceRequestOutcome
  evidence_ids: Array<string>
  attempted_at: string
}

export type EvidenceRequestOutcome = "AVAILABLE" | "UNAVAILABLE" | "UNSUPPORTED" | "ERROR" | "DUPLICATE_SKIPPED" | "ITERATION_LIMIT_REACHED"

export type EvidenceRequestType = "SHIFT_PRODUCTION" | "FLEET_SNAPSHOT" | "CYCLE_PERFORMANCE" | "DOWNTIME" | "SITE_ALERTS" | "ASSIGNMENTS" | "EQUIPMENT_TIMELINE" | "LOADING_CONTEXT" | "ZONE_CONTEXT" | "OEM_CONNECTIVITY" | "OEM_DIAGNOSTICS" | "OEM_ERRORS" | "OEM_MAINTENANCE_INDICATORS" | "EQUIPMENT_TELEMETRY_TRENDS" | "ROAD_NETWORK_CONTEXT" | "WEATHER_CONTEXT"

export type EvidenceStatus = "AVAILABLE" | "UNAVAILABLE" | "UNSUPPORTED" | "ERROR"

export type Hypothesis = {
  hypothesis_id: string
  statement: string
  supporting_evidence_ids: Array<string>
  contradictory_evidence_ids: Array<string>
  confidence: ConfidenceLevel
  causal_depth: number
  rationale: string
}

export type InvestigationConclusion = {
  summary: string
  diagnosis_status: DiagnosisStatus
  observed_condition: string | null
  root_cause: string | null
  reliable_root_cause: boolean
  causal_depth: number
  contributing_factors: Array<ContributingFactor>
  observed_fact_evidence_ids: Array<string>
  derived_metric_evidence_ids: Array<string>
  supported_hypothesis_ids: Array<string>
  unresolved_uncertainties: Array<string>
  confidence: ConfidenceLevel
}

export type InvestigationError = {
  stage: string
  error_type: string
  message: string
}

export type InvestigationRecommendation = {
  action_type: RecommendationAction
  description: string
  rationale: string
  evidence_ids: Array<string>
  target_equipment_id: number | null
  target_zone_id: number | null
  operational_constraints: Array<string>
  human_validation_required: boolean
}

export type InvestigationStatus = "PENDING" | "RESOLVING_CONTEXT" | "GATHERING_EVIDENCE" | "ANALYZING" | "BUILDING_CONCLUSION" | "BUILDING_RECOMMENDATION" | "COMPLETED" | "COMPLETED_WITH_UNCERTAINTY" | "FAILED"

export type InvestigationSubject = "PRODUCTION" | "EQUIPMENT" | "ZONE" | "CONNECTIVITY" | "MAINTENANCE" | "OTHER"

export type InvestigationTrigger = {
  trigger_type: TriggerType
  trigger_source: TriggerSource
  subject: InvestigationSubject | null
  source: string | null
  site_id: number
  shift_id: number | null
  equipment_id: number | null
  zone_id: number | null
  occurred_at: string
  severity: Severity | null
  source_record_id: string | null
  payload: Record<string, JsonValue>
}

export type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue }

export type RecommendationAction = "INSPECT_EQUIPMENT" | "VERIFY_OPERATIONAL_CONDITION" | "REVIEW_QUEUE_DISTRIBUTION" | "ESCALATE_TO_MAINTENANCE" | "CONSIDER_REASSIGNMENT" | "CONTINUE_MONITORING" | "NO_ACTION"

export type ResolvedOperationalContext = {
  site_id: number
  site_code: string
  site_name: string
  shift_id: number | null
  shift_name: string | null
  operational_now: string
  window_start: string
  window_end: string
}

export type Severity = "INFO" | "WARNING" | "CRITICAL"

export type TriggerSource = "AUTOMATIC_MONITORING" | "EXISTING_ALERT" | "USER_INVESTIGATE" | "CHAT_REQUEST"

export type TriggerType = "PRODUCTION_DEVIATION" | "EQUIPMENT_ANOMALY" | "CONGESTION_RISK" | "MAINTENANCE_RISK" | "PREDICTED_MECHANICAL_FAILURE_RISK" | "CONNECTIVITY_ISSUE" | "OPERATIONAL_EVENT"

export type InvestigationResult = {
  investigation_id: string
  trigger: InvestigationTrigger
  operational_context: ResolvedOperationalContext | null
  evidence: Array<EvidenceItem>
  hypotheses: Array<Hypothesis>
  requested_information: Array<EvidenceRequest>
  evidence_request_history: Array<EvidenceRequestAttempt>
  contradictions: Array<Contradiction>
  conclusion: InvestigationConclusion | null
  recommendation: InvestigationRecommendation | null
  iteration_count: number
  max_iterations: number
  iteration_limit_reached: boolean
  evidence_expansion_exhausted: boolean
  status: InvestigationStatus
  error: InvestigationError | null
  started_at: string
  completed_at: string | null
  graph_version: string
  provider: string
  model: string
}

export type InvestigationTriggerInput = {
  trigger_type: TriggerType
  trigger_source: TriggerSource
  subject?: InvestigationSubject | null
  source?: string | null
  site_id: number
  shift_id?: number | null
  equipment_id?: number | null
  zone_id?: number | null
  occurred_at?: string
  severity?: Severity | null
  source_record_id?: string | null
  payload?: Record<string, JsonValue>
}
