import enum


class EquipmentType(str, enum.Enum):
    HAUL_TRUCK = "HAUL_TRUCK"
    EXCAVATOR = "EXCAVATOR"
    LOADER = "LOADER"
    DOZER = "DOZER"
    GRADER = "GRADER"
    DRILL = "DRILL"
    WATER_TRUCK = "WATER_TRUCK"
    LIGHT_VEHICLE = "LIGHT_VEHICLE"
    OTHER = "OTHER"


class EquipmentState(str, enum.Enum):
    MOVING_EMPTY = "MOVING_EMPTY"
    MOVING_LOADED = "MOVING_LOADED"
    WAITING_LOADING = "WAITING_LOADING"
    WAITING_DUMPING = "WAITING_DUMPING"
    LOADING = "LOADING"
    DUMPING = "DUMPING"
    STOPPED_OPERATIONAL = "STOPPED_OPERATIONAL"
    STOPPED_MECHANICAL = "STOPPED_MECHANICAL"
    STOPPED_EXTERNAL = "STOPPED_EXTERNAL"
    STOPPED_UNDEFINED = "STOPPED_UNDEFINED"
    REFUELING = "REFUELING"
    MAINTENANCE = "MAINTENANCE"
    PARKED = "PARKED"
    ENGINE_OFF = "ENGINE_OFF"
    NO_DATA = "NO_DATA"
    UNKNOWN = "UNKNOWN"


class ZoneType(str, enum.Enum):
    LOADING_BENCH = "LOADING_BENCH"
    DUMP_AREA = "DUMP_AREA"
    CRUSHER = "CRUSHER"
    STOCKPILE = "STOCKPILE"
    FUEL_STATION = "FUEL_STATION"
    MAINTENANCE_WORKSHOP = "MAINTENANCE_WORKSHOP"
    PARKING = "PARKING"
    RESTRICTED_AREA = "RESTRICTED_AREA"
    SHIFT_CHANGE_AREA = "SHIFT_CHANGE_AREA"
    OTHER = "OTHER"


class AlertSeverity(str, enum.Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


class AlertStatus(str, enum.Enum):
    NEW = "NEW"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    INVESTIGATING = "INVESTIGATING"
    ASSIGNED = "ASSIGNED"
    RESOLVED = "RESOLVED"


class AlertSource(str, enum.Enum):
    FMS = "FMS"
    SENSOR = "SENSOR"
    RULE = "RULE"
    PREDICTION = "PREDICTION"
    AI = "AI"


class RecommendationStatus(str, enum.Enum):
    GENERATED = "GENERATED"
    MARKED = "MARKED"
    PREPARED = "PREPARED"
    VALIDATED = "VALIDATED"
    REJECTED = "REJECTED"
    IGNORED = "IGNORED"
